name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:1.22.5-alpine3.20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build .
# TODO: add go test